# INDUXING AND SCLICING 

In [2]:
import numpy as np


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2:5])  # Output: [3 4 5]
print(arr[:4])   # Output: [1 2 3 4]
print(arr[5::2]) # Output: [6 8 10]
print(arr[-3::2])  # Output: [8 10]
print(arr[-4:-8:-1])  # Output: [7 6 5 4]
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d[0,1,0:]) #[3 4] # layer by leyar ander chalo
print("2D array:\n", arr_2d)
print("specific element in 2D array index 1 row index 2:", arr_2d[1, 2])  # Output: 6 because it accesses the element in the second row (index 1) and third column (index 2) of the 2D array. indexing starts at 0, so the first row is index 0, the second row is index 1, and the third row is index 2. Similarly, the first column is index 0, the second column is index 1, and the third column is index 2.
print("specific element in 3D array:", arr_3d[0, 1, 0])  # Output: 3
print("2nd row of 2D array:", arr_2d[1, :])  # Output: [4 5 6] # second row
print("1st column of 2D array:", arr_2d[:, 0])  # Output: [1 4 7]
print("2nd layer of 3D array:", arr_3d[1, :, :])  # Output: [[5 6] [7 8]]
print("1st column of 2nd layer in 3D array:", arr_3d[1, :, 0])  # Output: [5 7]] # see carefully, the first index (1) selects the second layer, the second index (:) selects all rows, and the third index (0) selects the first column of that layer.it is all about the order of indexing and how it corresponds to the dimensions of the array.


[3 4 5]
[1 2 3 4]
[ 6  8 10]
[ 8 10]
[7 6 5 4]
[3 4]
2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element in 2D array index 1 row index 2: 6
specific element in 3D array: 3
2nd row of 2D array: [4 5 6]
1st column of 2D array: [1 4 7]
2nd layer of 3D array: [[5 6]
 [7 8]]
1st column of 2nd layer in 3D array: [5 7]


## sorting

In [4]:
unsorted_arr = np.array([3, 1, 4, 1, 5, 9,2,6,5,3,5])
sorted_arr = np.sort(unsorted_arr)
print("Sorted array:", sorted_arr)  # output: [1 1 2 3 3 4 5 5 5 6 9]

unsorted_arr_2d = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

SORTED_ARR_NEW = np.sort(unsorted_arr_2d, axis=None)
print("Sorted 2D array along both axes:\n", SORTED_ARR_NEW)

sorted_arr_2d = np.sort(unsorted_arr_2d, axis=0)
print("Sorted 2D array along columns:\n", sorted_arr_2d)

sorted_arr_2d_axis1 = np.sort(unsorted_arr_2d, axis=1)
print("Sorted 2D array along rows:\n", sorted_arr_2d_axis1)

Sorted array: [1 1 2 3 3 4 5 5 5 6 9]
Sorted 2D array along both axes:
 [1 1 2 3 4 5 5 6 9]
Sorted 2D array along columns:
 [[1 1 4]
 [2 5 5]
 [3 6 9]]
Sorted 2D array along rows:
 [[1 3 4]
 [1 5 9]
 [2 5 6]]


## FILTER


In [17]:
NUMBER = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = NUMBER[NUMBER % 2 == 0]   # NUMBER % 2 == 0 creates a boolean array where True corresponds to even numbers and False corresponds to odd numbers. When we use this boolean array to index the original NUMBER array, it returns only the elements that are even. IT WORK AS A MASKING OPERATION. 
print("Even numbers:", even_numbers)  # Output: [2 4 6 8 10]
Hero = NUMBER%2 != 0
odd_numbers = NUMBER[Hero]
print("Odd numbers:", odd_numbers)  # Output: [1 3 5 7 9]


Even numbers: [ 2  4  6  8 10]
Odd numbers: [1 3 5 7 9]


## FILTER WITH MASK

In [6]:
MASK = NUMBER > 5
filtered_numbers = NUMBER[MASK]
print("Numbers greater than 5:", filtered_numbers)  # Output: [6 7 8 9 10]

Numbers greater than 5: [ 6  7  8  9 10]


##  FANCY INDEXING VS NP.WHERE()
* where() contains indexs for condition true

In [ ]:
INDEX = [3,5,7]
print("Selected elements using index array:", NUMBER[INDEX], NUMBER)  # Output: [4 6 8],[ 1  2  3  4  5  6  7  8  9 10]

WHERE_MASK = np.where(NUMBER % 2 == 0) # WHERE ONLY STORE THE INDEX OF THE TRUE VALUE IN THE MASK.
print("Indices of even numbers:", WHERE_MASK)  # Output: (array([1, 3, 5, 7, 9]),) # np.where returns a tuple of arrays, where each array corresponds to the indices along a specific dimension where the condition is True. In this case, it returns a tuple with one array containing the indices of the even numbers in the original NUMBER array. The indices are 1, 3, 5, 7, and 9, which correspond to the positions of the even numbers (2, 4, 6, 8, and 10) in the original array.
print("Even numbers using np.where:", NUMBER[WHERE_MASK])  # Output: [2 4 6 8 10]


Selected elements using index array: [4 6 8] [ 1  2  3  4  5  6  7  8  9 10]
Indices of even numbers: (array([1, 3, 5, 7, 9]),)
Even numbers using np.where: [ 2  4  6  8 10]


## SELF LEARING


In [19]:
NUMS = np.arange(20)
print("Original array:", NUMS)
number_new = np.random.choice(NUMS, size=10, replace=True)  # This line of code generates a new array called number_new by randomly selecting 5 elements from the NUMS array. The replace=True argument allows for the possibility of selecting the same element multiple times, meaning that duplicates can occur in the resulting number_new array. If replace were set to False, each element could only be selected once, ensuring that all selected elements are unique.
print("Randomly selected numbers:", number_new)
filtered_numbers = number_new[number_new > 10]
print("Numbers greater than 10:", filtered_numbers)
# with index array
index_array = np.where(number_new > 10)
print("Indices of numbers greater than 10:", index_array)
print("number greater than 10 using index array:", number_new[index_array])



Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Randomly selected numbers: [13 15 11 19  6  8  3 12  0  7]
Numbers greater than 10: [13 15 11 19 12]
Indices of numbers greater than 10: (array([0, 1, 2, 3, 7]),)
number greater than 10 using index array: [13 15 11 19 12]


## CONDITION ARRAY  
* Ture --> 1st condition
* False --> 2nd condition

In [22]:
Given_num = number_new
print(Given_num)
conditional_arry = np.where(Given_num > 10, Given_num*2, Given_num*0)  # This line of code creates a new array called conditional_arry by applying a condition to the Given_num array. The np.where function takes three arguments: the condition (Given_num > 10), the value to use when the condition is True (Given_num*2), and the value to use when the condition is False (Given_num*0). For each element in the Given_num array, if it is greater than 10, it will be multiplied by 2 and included in the conditional_arry; otherwise, it will be included as is.
print("Conditional array based on Given_num:", conditional_arry)
print("Numbers greater than 10 multiplied by 2:", conditional_arry[conditional_arry > 0])  # This line of code filters the conditional_arry to include only the elements that are greater than 0, which correspond to the numbers that were greater than 10 in the original Given_num array and were multiplied by 2. The output will be an array of the numbers that were greater than 10, each multiplied by 2.

[13 15 11 19  6  8  3 12  0  7]
Conditional array based on Given_num: [26 30 22 38  0  0  0 24  0  0]
Numbers greater than 10 multiplied by 2: [26 30 22 38 24]


In [25]:
print("Given number:",Given_num)
num_get = []
for num in Given_num:
    if num > 10:
        num = num * 4
        num_get.append((num))
    else:
        num = num * 0
        num_get.append((num))
print("Numbers greater than 10 multiplied by 4:", (np.array(num_get).tolist()))



Given number: [13 15 11 19  6  8  3 12  0  7]
Numbers greater than 10 multiplied by 4: [52, 60, 44, 76, 0, 0, 0, 48, 0, 0]


### Adding and removing Data

In [29]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50]) # only for element-wise addition, not for concatenation
combined_arr = arr1 + arr2
print("Combined array (element-wise addition):", combined_arr)  # Output: [11 22 33 44 55]
combined_arr2 = np.concatenate((arr1, arr2))
print("Combined array using concatenate:", combined_arr2)  # Output: [ 1  2  3  4  5 10 20 30 40 50]
print(np.add(arr1, arr2))  # Output: [11 22 33 44 55]
arr3 = np.array([100, 200, 300])
print(arr1 + arr2 + arr3)  # Output: must have number of  element in adding list

Combined array (element-wise addition): [11 22 33 44 55]
Combined array using concatenate: [ 1  2  3  4  5 10 20 30 40 50]
[11 22 33 44 55]


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### Array compatibility


In [ ]:
a= np.array([1, 2, 3])
b= np.array([4,5,6])
c= np.array([7,8,8,9,10])
print("compatibility =", a.shape == b.shape) #same size and shape of the array. Output: True, because both arrays a and b have the same shape (3,). If the shapes were different, this would return False, indicating that the arrays are not compatible for element-wise operations.

print(np.add(a, b))  # Output: [5 7 9]
print(np.add(a, c))  # Output: ValueError: operands could not be broadcast together with shapes (3,) (5,)

compatibility = np.add(np.add(a, b), c) # By using this we can check compatibility of the arrays a, b, and c. The np.add function is used to perform element-wise addition between the arrays. First, it adds array a and array b together, resulting in an intermediate array. Then, it adds this intermediate array to array c, giving us the final result stored in the variable compatibility. The output will be an array where each element is the sum of the corresponding elements from arrays a, b, and c.
print("Compatibility of a, b, and c:", compatibility)  # Output: value error no same shape and size of the array. because a and b have the same shape (3,) but c has a different shape (5,). Therefore, they are not compatible for element-wise addition, and attempting to add them will result in a ValueError.  
print("compatibility =", a.shape == c.shape)  # Output: True, because all three arrays have the same shape (3,). If the shapes were different, this would return False, indicating that the arrays are not compatible for element-wise operations.


compatibility = False
[5 7 9]


ValueError: operands could not be broadcast together with shapes (3,) (5,) 

## Vstack vs Hstack
* Vstack --> add Hertically
* Hstack --> add Vertically

In [ ]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # it is a 3x3 array and 2D array only have two axis, the first axis (axis 0) represents the rows and the second axis (axis 1) represents the columns. In this case, the original array has 3 rows and 3 columns, so it is a 3x3 array. The shape of the original array is (3, 3), which indicates that it has 3 rows and 3 columns.
original2 = np.array([[1, 2, 3]]) # it is a 1x3 array and 2D array only have two axis, the first axis (axis 0) represents the rows and the second axis (axis 1) represents the columns. In this case, the original2 array has 1 row and 3 columns, so it is a 1x3 array. The shape of the original2 array is (1, 3), which indicates that it has 1 row and 3 columns.
with_new_one_arrow = np.vstack((original, np.array([[1, 88, 99]]))) # The np.vstack function is used to stack arrays vertically (row-wise). In this case, it takes the original array and stacks the original2 array on top of it. The resulting with_new_one array will have the shape (4, 3), meaning it has 4 rows and 3 columns. The new array is added as a new row at the bottom of the original array.
print(with_new_one_arrow)
with_new_column = np.hstack((original, np.array([[1], [88], [99]]))) # The np.hstack function is used to stack arrays horizontally (column-wise). In this case, it takes the original array and stacks a new array (with values 1, 88, and 99) as a new column on the right side of the original array. The resulting with_new_column array will have the shape (3, 4), meaning it has 3 rows and 4 columns. The new array is added as a new column at the end of the original array.
print(with_new_column)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 1 88 99]]
[[ 1  2  3  1]
 [ 4  5  6 88]
 [ 7  8  9 99]]


In [ ]:
##### Deleting the arrays we created
array1 = np.array([2, 4, 6, 8, 10])
print(np.delete(array1, [0, 2])) # delete index of 0 and 2, which means it will remove the elements at those indices from the array. The resulting array will be [4, 8, 10], as the elements at index 0 (2) and index 2 (6) are removed.
print(np.delete(array1 , 3)) # delete index of 3, which means it will remove the element at that index from the array. The resulting array will be [2, 4, 6, 10], as the element at index 3 (8) is removed.


[ 4  8 10]
[ 2  4  6 10]
