### Numpy array and Basic 
Learn about numpy with chaiwithcode

In [2]:
import numpy as np


# Creating Array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)
arr_3d = np.array([[1, 2], [3, 4], [5, 6]])
print("3D array:\n", arr_3d)
arr_4d = np.array([[[1, 2,3 ], [3, 4,5]], [[5, 6,7], [7, 8,9]]])
arr_4d2 = arr_4d.reshape(2, 2, 3, 1)  # Reshape to 4D array
print("4D array:\n", arr_4d)
print("Reshaped 4D array:\n", arr_4d2)
print("Shape of 1D array:", arr_1d.shape) #only one row and five columns
print("Shape of 2D array:", arr_2d.shape) #only two rows and three columns
print("Shape of 3D array:", arr_3d.shape) #only three rows and two columns
print("Shape of 4D array:", arr_4d.shape) #only two rows, two columns, and three depth
print("Shape of reshaped 4D array:", arr_4d2.shape) #only two rows, two columns, three depth, and one channel


1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[1 2]
 [3 4]
 [5 6]]
4D array:
 [[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
Reshaped 4D array:
 [[[[1]
   [2]
   [3]]

  [[3]
   [4]
   [5]]]


 [[[5]
   [6]
   [7]]

  [[7]
   [8]
   [9]]]]
Shape of 1D array: (5,)
Shape of 2D array: (2, 3)
Shape of 3D array: (3, 2)
Shape of 4D array: (2, 2, 3)
Shape of reshaped 4D array: (2, 2, 3, 1)


In [4]:
X = [1,2,3,4,5]
print(X*2)
print(list(map(lambda x: x*2, X)))
print(np.array(X)*2)   # multiplying a numpy array by 2 will multiply each element by 2
print(list(map(lambda x: x*2 , X)))

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]
[2, 4, 6, 8, 10]


In [5]:
py_list = [1, 2, 3, 4, 5]
print("python list multiplied by 2:", py_list * 2)

python list multiplied by 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
py_array = [1, 2, 3, 4, 5 ]
print("python array multiplied by 2:", np.array(py_array) * 2)

python array multiplied by 2: [ 2  4  6  8 10]


### Efficiency checking of array and list


In [7]:
import time
import numpy as np


# ============================================================
# 1. PYTHON LIST
# ============================================================

start = time.time()                         # Start the timer

x = list(i for i in range(1000000))         # Create a Python list
                                             # containing 1,000,000 numbers

end = time.time()                           # Stop the timer

print("List Time taken:", end - start)      # Print execution time


# ============================================================
# 2. PYTHON LIST → NUMPY ARRAY
# ============================================================

start = time.time()                         # Start the timer

x = np.array([i for i in range(1000000)])   # First create a Python list
                                             # Then convert it into a NumPy array

end = time.time()                           # Stop the timer

print("NumPy Array Time taken:", end - start)


# ============================================================
# 3. NUMPY arange()
# ============================================================

start = time.time()                         # Start the timer

p = np.arange(1000000)                      # Directly create a NumPy array
                                             # containing numbers 0 to 999999

end = time.time()                           # Stop the timer

print("NumPy Time taken:", end - start)


# ============================================================
# 4. PYTHON range()
# ============================================================

start = time.time()                         # Start the timer

p = range(1000000)                          # Create a Python range object
                                             # Numbers are generated when needed

end = time.time()                           # Stop the timer

print("Python range Time taken:", end - start)

List Time taken: 0.09033203125
NumPy Array Time taken: 0.13918781280517578
NumPy Time taken: 0.002633333206176758
Python range Time taken: 0.00042819976806640625


### Conclusion

* `range()` creates a Python range object and generates values when needed, so it is very fast and memory efficient.
* `list()` stores all the elements in a Python list, so it requires more memory.
* `np.array()` converts a Python list into a NumPy array, so it involves an extra conversion step.
* `np.arange()` directly creates a NumPy array and is generally more efficient for creating numerical sequences.
* Therefore, **`range()` and `np.arange()` are not exactly equivalent**: `range()` creates a sequence object, while `np.arange()` creates and stores an actual NumPy array.
* For numerical computing and large arrays, **NumPy is generally preferred** because it provides efficient storage and fast numerical operations.


### Creating array from scratch


In [8]:
import numpy as np

zeros = np.zeros((2, 3))       # Creates 2×3 array filled with 0
print("Zeros:\n", zeros)

ones = np.ones((2, 3))        # Creates 2×3 array filled with 1
print("Ones:\n", ones)

full = np.full((2, 3), 7)     # Creates 2×3 array filled with 7
print("Full:\n", full)

eye = np.eye(4)               # Creates 4×4 identity matrix
print("Identity:\n", eye)

random = np.random.rand(2, 3) # Creates 2×3 array of random values (0 to 1)
print("Random:\n", random)



Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7]
 [7 7 7]]
Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random:
 [[0.00126587 0.8805427  0.13137665]
 [0.47486611 0.9775216  0.5881608 ]]


In [13]:
random_int = np.random.randint(1, 10, size=(2, 3))
print("Random integer array:\n", random_int)

random_normal = np.random.normal(loc=1, scale=3, size=(2, 3))  # negative sign value is not allowed in scale parameter, it will raise an error. but output can be negative due to the nature of normal distribution.Yahan mean/average un random numbers ka hota hai jo normal distribution se generate ho rahe hain.
"""loc=1 → generated values ka theoretical mean (average) = 1
scale=3 → un values ka standard deviation = 3
size=(2,3) → total 6 random values"""
print("Random normal array:\n", random_normal)

random_seed = np.random.seed(10) # it will set the random seed to 32, which means that the same sequence of random numbers will be generated each time the code is run. This is useful for reproducibility and debugging purposes. here we are setting the random seed to 32, so the random numbers generated will be the same every time we run this code. If we set the seed to a different value, we will get a different sequence of random numbers. 
print("Random seed set to 32.")
random_seed_array = np.random.rand(2, 3) # it will generate a 2x3 array of random numbers between 0 and 1, using the random seed that we set earlier. Since we set the seed to 32, the same random numbers will be generated every time we run this code. If we set the seed to a different value, we will get a different sequence of random numbers.
print("Random array with seed:\n", random_seed_array)   
print("Random array with seed again:\n", np.random.rand(2, 3))


sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence)

# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

# number of dimensions
print(random_int.ndim)
print(random_int.dtype)


Random integer array:
 [[7 9 2]
 [9 5 2]]
Random normal array:
 [[ 1.68589039  2.33541284 -2.40980664]
 [ 1.40541064  5.45361101 -2.23941466]]
Random seed set to 32.
Random array with seed:
 [[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]]
Random array with seed again:
 [[0.19806286 0.76053071 0.16911084]
 [0.08833981 0.68535982 0.95339335]]
Sequence array: 
 [0 2 4 6 8]
[10. 15. 20. 25. 30.]
[10 15 20 25]
2
int32


# Vector, Matrix, Tensor 

In [10]:
vector = np.array([1, 2, 3])
print("Vector:\n", vector)

matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
print("Matrix:\n", matrix) 

tensor = np.array([[[1, 2, 3],[4, 5, 6]],
                    [[7, 8, 9],[10, 11, 12]]])
print("Tensor:\n", tensor)


Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Arrray properties


In [11]:
arr = np. array([[1, 2, 3],
                  [4, 5, 6]])
print("shape of arr:", arr.shape)
print("number of dimensions of arr:", arr.ndim) # number of dimensions in the array. In this case, arr has 2 dimensions (rows and columns), so the output will be 2.
print("size of arr:", arr.size) # total number of elements in the array, which is the product of the dimensions. In this case, arr has 2 rows and 3 columns, so the total number of elements is 2 * 3 = 6.
print("data type of arr:", arr.dtype) # data type of the elements in the array. In this case, the elements are integers, so the output will be int64 (or int32 depending on the system).

shape of arr: (2, 3)
number of dimensions of arr: 2
size of arr: 6
data type of arr: int64


## Array reshaping

In [12]:
import numpy as np

# Create array with values 0 to 19
arr = np.arange(20)
print("Original:", arr)

# Access first element
print("arr[0]:", arr[0])


# Reshape: changes shape, returns a new array
reshaped_arr = arr.reshape((5, 4))
print("Reshaped:\n", reshaped_arr)


# 3D reshape: 4 × 5 × 1 = 20 elements
reshaped_arr_3d = arr.reshape((4, 5, 1))
print("3D Reshaped:\n", reshaped_arr_3d)


# Resize: changes the original array in-place
arr.resize((4, 5))
print("Resized:\n", arr)


# Flatten: converts to 1D and returns a COPY
flattened = reshaped_arr.flatten()
print("Flattened:", flattened)


# Ravel: converts to 1D and returns a VIEW when possible
ravelled = reshaped_arr.ravel()
print("Ravelled:", ravelled)


# Transpose: swaps rows and columns
transposed = reshaped_arr.T
print("Transposed:\n", transposed)


# Adjoint: conjugate transpose
# For real numbers, adjoint = transpose
adjoint = reshaped_arr.conj().T
print("Adjoint:\n", adjoint)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
arr[0]: 0
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
3D Reshaped:
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]]
Resized:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Ravelled: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Transposed:
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
Adjoint:
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


reshape() → original array ko change NAHI karta
             → new shaped array return karta hai

resize()  → original array ko HI change karta hai
             → in-place modify karta hai